"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { api } from "../lib/api";
import { Application, Page } from "../lib/applications";
import { formatCurrency } from "../lib/finance";

type Priority = "LOWER_EMI" | "LOWER_TOTAL_INTEREST" | "BALANCED";
type Stress = { income_drop_percent:number; stressed_take_home_income:string; debt_service_ratio:number|null; stressed_residual:string; goal_adjusted_residual:string|null };
type Scenario = { term_months:number; annual_rate_percent:string; emi:string; total_repayment:string; total_interest:string; current_dti:number|null; proposed_debt_to_income_ratio:number|null; current_take_home_payment_ratio:number|null; proposed_take_home_payment_ratio:number|null; residual_monthly_income:string; goal_adjusted_residual:string|null; additional_emi_headroom:string|null; planning_fit_score:number; score_components:{payment_burden:number;residual_cash_flow:number}; fits_stated_budget:boolean; savings_goal_fit:boolean|null; stress:Stress[]; monthly_room_score:number; interest_saving_score:number; rank_score:number; rank:number; rank_explanation:string };
type Plan = { calculation_version:string; currency:"INR"; as_of:string; current_debt_burden_monthly:string; current_dti:number|null; current_take_home_payment_ratio:number; total_outstanding_debt:string|null; liquid_savings:string|null; monthly_essential_expenses:string; monthly_savings_goal:string|null; additional_emi_headroom:string|null; additional_emi_headroom_before_savings_goal:string; savings_buffer_months:number|null; planning_priority:Priority; ranking_weights:{monthly_room:number;interest_saving:number}; scenarios:Scenario[]; warnings:string[] };
type Inputs = { application_id:string; monthly_take_home_income:string; monthly_gross_income:string; monthly_essential_expenses:string; existing_monthly_debt_payments:string; total_outstanding_debt:string; liquid_savings:string; monthly_savings_goal:string; requested_amount:string; annual_rate_percent:string; terms:string; planning_priority:Priority; loan_purpose:string };

const DEFAULTS:Inputs = { application_id:"", monthly_take_home_income:"", monthly_gross_income:"", monthly_essential_expenses:"", existing_monthly_debt_payments:"0", total_outstanding_debt:"", liquid_savings:"", monthly_savings_goal:"", requested_amount:"", annual_rate_percent:"12", terms:"12,24,36,48,60", planning_priority:"BALANCED", loan_purpose:"" };
const percent=(value:number|null|undefined)=>value===null||value===undefined?"Not provided":`${(value*100).toFixed(1)}%`;
const amount=(value:string|null|undefined)=>value===null||value===undefined?"Not provided":formatCurrency(value);

export default function BorrowingPlanner(){
 const [inputs,setInputs]=useState<Inputs>(DEFAULTS),[applications,setApplications]=useState<Application[]>([]),[applicationLabel,setApplicationLabel]=useState(""),[plan,setPlan]=useState<Plan|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;api<Page<Application>>("/applications?limit=100&offset=0").then(page=>{if(active)setApplications(page.items);}).catch(()=>{if(active)setApplications([]);});return()=>{active=false;};},[]);
 const ranked=plan?.scenarios??[];const recommended=ranked[0];
 const stressRows=useMemo(()=>ranked.flatMap(s=>s.stress.map(t=>({term:s.term_months,...t}))),[ranked]);
 function set<K extends keyof Inputs>(key:K,value:Inputs[K]){setInputs(current=>({...current,[key]:value}));}
 async function chooseApplication(id:string){set("application_id",id);setPlan(null);setApplicationLabel("");if(!id)return;try{const item=await api<Application>(`/applications/${id}`);const income=String(item.input?.annual_income??"");set("requested_amount",item.requested_amount);if(item.quote)set("terms",String(item.quote.term_months));setApplicationLabel(income?`Application income on record: ${formatCurrency(income)} per year (reference only; confirm your current monthly amounts below).`:"Application selected. Confirm your current monthly amounts below.");}catch(e){setError((e as Error).message);}}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");setPlan(null);try{
  const terms=inputs.terms.split(",").map(value=>value.trim()).filter(Boolean).map(Number);
  const body:Record<string,unknown>={currency:"INR",...(inputs.application_id?{application_id:inputs.application_id}:{}),monthly_take_home_income:inputs.monthly_take_home_income,monthly_essential_expenses:inputs.monthly_essential_expenses,existing_monthly_debt_payments:inputs.existing_monthly_debt_payments,requested_amount:inputs.requested_amount,annual_rate_percent:inputs.annual_rate_percent,terms_months:terms,planning_priority:inputs.planning_priority,...(inputs.monthly_gross_income!==""?{monthly_gross_income:inputs.monthly_gross_income}:{}),...(inputs.total_outstanding_debt!==""?{total_outstanding_debt:inputs.total_outstanding_debt}:{}),...(inputs.liquid_savings!==""?{liquid_savings:inputs.liquid_savings}:{}),...(inputs.monthly_savings_goal!==""?{monthly_savings_goal:inputs.monthly_savings_goal}:{}),...(inputs.loan_purpose?{loan_purpose:inputs.loan_purpose}:{})};
  setPlan(await api<Plan>("/planner/plan",{method:"POST",body:JSON.stringify(body)}));
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><div className="eyebrow">Cash-flow planning</div><h1>Borrowing Planner</h1><p>Compare illustrative repayments against the monthly budget you provide.</p><div className="notice planner-disclaimer">Planning estimates only. They are not an offer, eligibility decision, or financial advice. Entered values are unverified; INR is user-confirmed and no currency conversion occurs.</div>
 <form onSubmit={submit}>
  {applications.length>0&&<section className="panel"><h2>Start from an application (optional)</h2><label>Choose an application<select value={inputs.application_id} onChange={e=>chooseApplication(e.target.value)}><option value="">Enter a plan from scratch</option>{applications.map((item,index)=><option key={item.id} value={item.id}>{new Date(item.created_at).toLocaleDateString("en-IN")} · {formatCurrency(item.requested_amount)} · v{item.version||index+1}</option>)}</select></label>{applicationLabel&&<p className="muted">{applicationLabel}</p>}<p className="muted">Only requested amount and term are prefilled. Your current income, expenses and debt payments must be entered and confirmed below.</p></section>}
  <section className="panel"><h2>Your monthly finances</h2><div className="formgrid">
   <label>Monthly take-home income (₹)<input aria-label="Monthly take-home income" type="number" min="0.01" max="1000000000" step="0.01" required value={inputs.monthly_take_home_income} onChange={e=>set("monthly_take_home_income",e.target.value)}/></label>
   <label>Monthly gross income (optional, for DTI)<input aria-label="Monthly gross income" type="number" min="0.01" max="1000000000" step="0.01" value={inputs.monthly_gross_income} onChange={e=>set("monthly_gross_income",e.target.value)}/></label>
   <label>Essential monthly expenses (exclude debt payments)<input aria-label="Essential monthly expenses" type="number" min="0" max="1000000000" step="0.01" required value={inputs.monthly_essential_expenses} onChange={e=>set("monthly_essential_expenses",e.target.value)}/></label>
   <label>Existing monthly debt payments (enter 0 if none)<input aria-label="Existing monthly debt payments" type="number" min="0" max="1000000000" step="0.01" required value={inputs.existing_monthly_debt_payments} onChange={e=>set("existing_monthly_debt_payments",e.target.value)}/></label>
   <label>Total outstanding debt (optional)<input aria-label="Total outstanding debt" type="number" min="0" max="1000000000" step="0.01" value={inputs.total_outstanding_debt} onChange={e=>set("total_outstanding_debt",e.target.value)}/></label>
   <label>Liquid savings (optional)<input aria-label="Liquid savings" type="number" min="0" max="1000000000" step="0.01" value={inputs.liquid_savings} onChange={e=>set("liquid_savings",e.target.value)}/></label>
   <label>Monthly savings goal (leave blank if unknown; enter 0 if none)<input aria-label="Monthly savings goal" type="number" min="0" max="1000000000" step="0.01" value={inputs.monthly_savings_goal} onChange={e=>set("monthly_savings_goal",e.target.value)}/></label>
  </div><p className="muted">Current debt payments include active EMIs, card minimums and other credit payments. Expenses must not include those payments.</p></section>
  <section className="panel"><h2>Loan scenarios</h2><div className="formgrid">
   <label>Requested amount (₹)<input aria-label="Requested amount" type="number" min="0.01" max="1000000000" step="0.01" required value={inputs.requested_amount} onChange={e=>set("requested_amount",e.target.value)}/></label>
   <label>Illustrative annual rate (%)<input aria-label="Illustrative annual rate" type="number" min="0" max="1000" step="0.0001" required value={inputs.annual_rate_percent} onChange={e=>set("annual_rate_percent",e.target.value)}/></label>
   <label>Terms in months, comma separated<input aria-label="Terms in months" inputMode="numeric" required value={inputs.terms} onChange={e=>set("terms",e.target.value)}/></label>
   <label>What matters most?<select aria-label="Planning priority" value={inputs.planning_priority} onChange={e=>set("planning_priority",e.target.value as Priority)}><option value="BALANCED">Balance monthly room and total interest</option><option value="LOWER_EMI">Lower monthly EMI</option><option value="LOWER_TOTAL_INTEREST">Lower total interest</option></select></label>
   <label>Loan purpose (optional)<input aria-label="Loan purpose" maxLength={120} value={inputs.loan_purpose} onChange={e=>set("loan_purpose",e.target.value)}/></label>
  </div><p className="muted">Terms must be unique whole months from 6 to 360 (up to 12 terms). The default rate is 12%, editable for illustration only. Fees and lender-specific pricing are excluded.</p><button className="btn" disabled={busy}>{busy?"Calculating scenarios…":"Compare borrowing scenarios"}</button></section>
 </form>
 {error&&<div className="error" role="alert">{error}</div>}
 {plan&&recommended&&<section aria-label="Borrowing plan results"><div className="planner-results-heading"><div><div className="eyebrow">Scenario comparison · {plan.calculation_version}</div><h2>Your monthly plan</h2></div><span className="badge">Ranked for {plan.planning_priority.replaceAll("_"," ").toLowerCase()}</span></div>
  <section className="panel"><h2>Cash-flow summary</h2><dl className="financial-grid planner-cashflow"><div><dt>Take-home income</dt><dd>{formatCurrency(inputs.monthly_take_home_income)}</dd></div><div><dt>Essential expenses</dt><dd>{formatCurrency(inputs.monthly_essential_expenses)}</dd></div><div><dt>Existing debt payments</dt><dd>{amount(plan.current_debt_burden_monthly)}</dd></div><div><dt>Requested amount</dt><dd>{formatCurrency(inputs.requested_amount)}</dd></div><div><dt>Recommended scenario EMI · {recommended.term_months} mo</dt><dd>{amount(recommended.emi)}</dd></div><div><dt>Residual after EMI</dt><dd>{amount(recommended.residual_monthly_income)}</dd></div><div><dt>Monthly savings goal</dt><dd>{amount(plan.monthly_savings_goal)}</dd></div><div><dt>After savings goal</dt><dd>{amount(recommended.goal_adjusted_residual)}</dd></div><div><dt>Current DTI</dt><dd>{percent(plan.current_dti)}</dd></div><div><dt>Proposed DTI</dt><dd>{percent(recommended.proposed_debt_to_income_ratio)}</dd></div><div><dt>Debt / take-home after EMI</dt><dd>{percent(recommended.proposed_take_home_payment_ratio)}</dd></div><div><dt>Total outstanding debt</dt><dd>{amount(plan.total_outstanding_debt)}</dd></div><div><dt>Liquid savings</dt><dd>{amount(plan.liquid_savings)}</dd></div><div><dt>Additional EMI headroom after savings goal</dt><dd>{amount(plan.additional_emi_headroom)}</dd></div><div><dt>Headroom before savings goal</dt><dd>{amount(plan.additional_emi_headroom_before_savings_goal)}</dd></div><div><dt>Savings buffer</dt><dd>{plan.savings_buffer_months===null?"Not provided":`${plan.savings_buffer_months.toFixed(1)} months`}</dd></div></dl></section>
  <section className="panel planner-score"><div><div className="eyebrow">Indicative cash-flow heuristic</div><h2>Planning Fit Score</h2><p>Separate from your Lite risk estimate, Affordability score and repayment history.</p></div><strong className="planner-score-value">{recommended.planning_fit_score}<small> / 100</small></strong><div className="planner-score-parts"><span>Payment burden: {recommended.score_components.payment_burden} / 60</span><span>Residual cash flow: {recommended.score_components.residual_cash_flow} / 40</span></div></section>
  <section className="panel"><h2>Loan scenario comparison</h2><div className="tablewrap"><table className="planner-table"><thead><tr><th>Rank</th><th>Term</th><th>Monthly EMI</th><th>Total interest</th><th>Total repayment</th><th>Residual after EMI</th><th>Plan fit</th><th>Ranking explanation</th></tr></thead><tbody>{ranked.map(s=><tr key={s.term_months}><td><strong>#{s.rank}</strong><small>Score {s.rank_score.toFixed(2)}</small></td><td>{s.term_months} months</td><td>{amount(s.emi)}</td><td>{amount(s.total_interest)}</td><td>{amount(s.total_repayment)}</td><td>{amount(s.goal_adjusted_residual??s.residual_monthly_income)}</td><td><span className={`badge ${s.fits_stated_budget?"Low":"High"}`}>{s.fits_stated_budget?"Fits stated budget":"Above stated budget"}</span><small>{s.savings_goal_fit===null?"Savings goal fit unknown":s.savings_goal_fit?"Meets savings goal":"Misses savings goal"}</small></td><td>{s.rank_explanation}</td></tr>)}</tbody></table></div><p className="muted">Rank score weights: {plan.ranking_weights.monthly_room*100}% monthly room · {plan.ranking_weights.interest_saving*100}% interest saving. The top rank is a comparison preference, not an eligibility result.</p></section>
  <section className="panel"><h2>Income stress test</h2><p>Expenses and current debt payments are held constant while take-home income changes.</p><div className="tablewrap"><table className="planner-table"><thead><tr><th>Term</th><th>Income reduction</th><th>Stressed income</th><th>Debt payment ratio</th><th>Residual</th><th>After savings goal</th></tr></thead><tbody>{stressRows.map((row,index)=><tr key={`${row.term}-${row.income_drop_percent}-${index}`}><td>{row.term} months</td><td>{row.income_drop_percent}%</td><td>{amount(row.stressed_take_home_income)}</td><td>{percent(row.debt_service_ratio)}</td><td>{amount(row.stressed_residual)}</td><td>{amount(row.goal_adjusted_residual)}</td></tr>)}</tbody></table></div></section>
  <section className="notice planner-disclaimer">{plan.warnings.map(w=><p key={w}>{w}</p>)}</section>
 </section>}
 </>;
}
