"use client";

import { useEffect, useState } from 'react';
import { CartesianGrid, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis } from 'recharts';
import { api } from '../lib/api';

type Profile = { cluster_id:number; cluster_size:number; cluster_percentage:number; mean_income_annual:number; mean_debt_requested_amount:number; mean_credit_utilization:number|null; mean_inquiries_1m:number; mean_inquiries_3m:number; mean_inquiries_12m:number; mean_payment_income_ratio:number; mean_principal_income_ratio:number; mean_payment_principal_ratio:number; mean_loan_to_goods_price_ratio:number; mean_age_years:number; mean_employment_years:number; description:string; debt_definition:string };
type KMetric = { k:number; silhouette_score:number; davies_bouldin_index:number; inertia:number; minimum_cluster_share:number; eligible_by_minimum_share:boolean };
type Point = { pca_1:number; pca_2:number; cluster_id:number };
type Dashboard = { mode:string; release_ready:boolean; run_id:string; source:{contract:string;run_id:string;rows:number;feature_count:number}; selected_k:number; methodology:{k_evaluated:number[];minimum_cluster_share:number;silhouette_tolerance:number;rule:string;fit_sample_size:number;metric_sample_size:number;inertia_basis:string}; selection_metrics:KMetric[]; final_model:{algorithm:string;n_clusters:number;n_init:number;max_iter:number;random_state:number}; profiles:Profile[]; pca:{explained_variance_ratio:number[];points:Point[]}; limitations:string[] };
const colors=['#0f766e','#4f46e5','#ea580c','#0891b2','#9333ea','#65a30d','#db2777','#475569','#ca8a04'];
const researchNumber=(value:number|null|undefined,digits=1)=>value==null?'Unavailable':new Intl.NumberFormat('en-IN',{maximumFractionDigits:digits}).format(value);

export default function CustomerSegmentationDashboard(){
 const [data,setData]=useState<Dashboard|null>(null);const [error,setError]=useState('');
 useEffect(()=>{let active=true;api<Dashboard>('/admin/customer-segmentation').then(value=>{if(active)setData(value);}).catch(reason=>{if(active)setError((reason as Error).message);});return()=>{active=false;};},[]);
 if(error)return <><div className="eyebrow">Admin · Research</div><h1>Customer Segmentation</h1><div className="error" role="alert">{error}</div></>;
 if(!data)return <main><p role="status">Loading saved segmentation artifacts…</p></main>;
 const plotted=data.pca.points.filter((_,index)=>index%4===0);
 const selectedMetric=data.selection_metrics.find(row=>row.k===data.selected_k);
 return <main className="segmentation-dashboard">
  <div className="page-heading"><div><div className="eyebrow">Admin · Unsupervised research</div><h1>Customer Segmentation</h1><p>Exploratory customer group profiles from the saved FULL_RESEARCH_V1_NO_EXT dataset.</p></div><span className="badge research-only">RESEARCH_ONLY · release_ready=false</span></div>
  <div className="notice research-notice">Segments describe patterns in a historical dataset. They are not risk labels, applicant scores, recommendations, or lending decisions.</div>

  <section className="panel"><div className="section-heading"><div><h2>Segment distribution</h2><p className="muted">{data.source.rows.toLocaleString()} records · {data.selected_k} neutral segments · run {data.run_id}</p></div></div><div className="segment-cards">{data.profiles.map((profile,index)=><article className="card" key={profile.cluster_id}><span className="segment-swatch" style={{backgroundColor:colors[index%colors.length]}}/><span className="muted">Segment {profile.cluster_id}</span><strong className="metric">{profile.cluster_size.toLocaleString()}</strong><p>{profile.cluster_percentage.toFixed(2)}% of dataset</p><p className="segment-description">{profile.description}</p></article>)}</div></section>

  <section className="panel"><div className="section-heading"><div><h2>Feature profiles</h2><p className="muted">Means by segment. Amounts are unspecified research units; income period follows the dataset assumption.</p></div></div><div className="tablewrap"><table className="segment-table"><thead><tr><th>Segment</th><th>Count</th><th>Income / year</th><th>Requested principal</th><th>Credit utilization</th><th>Inquiries · 1m</th><th>Inquiries · 3m</th><th>Inquiries · 12m</th><th>Payment / income</th><th>Principal / income</th><th>Payment / principal</th><th>Loan / goods price</th><th>Age</th><th>Employment years</th></tr></thead><tbody>{data.profiles.map(profile=><tr key={profile.cluster_id}><th scope="row">Segment {profile.cluster_id}</th><td>{profile.cluster_size.toLocaleString()} ({profile.cluster_percentage.toFixed(2)}%)</td><td>{researchNumber(profile.mean_income_annual)}</td><td>{researchNumber(profile.mean_debt_requested_amount)}</td><td>{researchNumber(profile.mean_credit_utilization,3)}</td><td>{researchNumber(profile.mean_inquiries_1m,3)}</td><td>{researchNumber(profile.mean_inquiries_3m,3)}</td><td>{researchNumber(profile.mean_inquiries_12m,3)}</td><td>{researchNumber(profile.mean_payment_income_ratio,3)}</td><td>{researchNumber(profile.mean_principal_income_ratio,3)}</td><td>{researchNumber(profile.mean_payment_principal_ratio,3)}</td><td>{researchNumber(profile.mean_loan_to_goods_price_ratio,3)}</td><td>{researchNumber(profile.mean_age_years,1)}</td><td>{researchNumber(profile.mean_employment_years,1)}</td></tr>)}</tbody></table></div><p className="muted">Requested principal is the current application's requested amount, not total existing liabilities. Credit utilization is unavailable in this feature contract and is not inferred from payment ratios.</p></section>

  <section className="panel"><div className="section-heading"><div><h2>PCA visualization</h2><p className="muted">A deterministic sample of {plotted.length.toLocaleString()} records projected to two principal components from the standardized clustering features.</p></div></div><div className="segment-pca-chart" role="img" aria-label="PCA scatterplot of sampled customer records colored by neutral segment"><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{top:12,right:22,bottom:24,left:8}}><CartesianGrid strokeDasharray="3 3"/><XAxis type="number" dataKey="pca_1" name="PCA 1" tick={{fontSize:11}}/><YAxis type="number" dataKey="pca_2" name="PCA 2" tick={{fontSize:11}}/><Tooltip cursor={{strokeDasharray:'3 3'}} formatter={(value)=>Number(value).toFixed(3)}/>{data.profiles.map((profile,index)=><Scatter key={profile.cluster_id} name={`Segment ${profile.cluster_id}`} data={plotted.filter(point=>point.cluster_id===profile.cluster_id)} fill={colors[index%colors.length]} fillOpacity={0.48} r={2}/>)}</ScatterChart></ResponsiveContainer></div><div className="segment-legend">{data.profiles.map((profile,index)=><span key={profile.cluster_id}><i style={{backgroundColor:colors[index%colors.length]}}/>Segment {profile.cluster_id}</span>)}</div><p className="muted">Explained variance: PCA 1 {researchNumber(data.pca.explained_variance_ratio[0]*100,2)}% · PCA 2 {researchNumber(data.pca.explained_variance_ratio[1]*100,2)}%. The projection is for visualization and does not validate cluster quality.</p></section>

  <section className="panel"><div className="section-heading"><div><h2>Methodology and K selection</h2><p className="muted">Selected K={data.selected_k}; StandardScaler follows median imputation and categorical one-hot encoding.</p></div></div>{selectedMetric&&selectedMetric.silhouette_score<.1&&<div className="notice segment-quality">Selected silhouette is modest ({selectedMetric.silhouette_score.toFixed(4)}), indicating weak separation. Treat these groups as exploratory and overlapping.</div>}<p>{data.methodology.rule}</p><p className="muted">Candidate fitting sample: {data.methodology.fit_sample_size.toLocaleString()} · metric sample: {data.methodology.metric_sample_size.toLocaleString()} · final K-Means fit: {data.source.rows.toLocaleString()} rows · random seed {data.final_model.random_state}. Inertia uses the candidate fitting sample and is reported as a diagnostic.</p><div className="tablewrap"><table className="segment-table segment-metrics"><thead><tr><th>K</th><th>Silhouette</th><th>Davies-Bouldin</th><th>Inertia · sample</th><th>Minimum cluster share</th><th>Eligible</th></tr></thead><tbody>{data.selection_metrics.map(row=><tr className={row.k===data.selected_k?'selected-k':''} key={row.k}><th scope="row">{row.k}{row.k===data.selected_k?' · selected':''}</th><td>{row.silhouette_score.toFixed(4)}</td><td>{row.davies_bouldin_index.toFixed(4)}</td><td>{row.inertia.toFixed(2)}</td><td>{(row.minimum_cluster_share*100).toFixed(2)}%</td><td>{row.eligible_by_minimum_share?'Yes':'Filtered'}</td></tr>)}</tbody></table></div></section>

  <section className="panel segmentation-limitations"><div className="section-heading"><div><h2>Limitations</h2><p className="muted">Research only · source contract {data.source.contract}, run {data.source.run_id}</p></div></div><ul>{data.limitations.map(note=><li key={note}>{note}</li>)}</ul></section>
 </main>;
}
