"use client";
import { ResponsiveContainer, PieChart, Pie, Cell, Tooltip, LineChart, Line, XAxis, YAxis, CartesianGrid } from "recharts";
import { dashboardAnalytics, Application } from "../lib/applications";
const COLORS=['#22C55E','#F59E0B','#EF4444'];
export default function DashboardCharts({items}:{items:Application[]}) {
  const data=dashboardAnalytics(items);
  return <div className="chart-grid"><section className="panel"><h2>Risk Distribution</h2>{data.scored?<><div className="chart" role="img" aria-label={data.distribution.map(d=>`${d.name}: ${d.value}`).join(', ')}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.distribution} dataKey="value" nameKey="name" innerRadius={62} outerRadius={88} paddingAngle={3} isAnimationActive={false}>{data.distribution.map((d,i)=><Cell key={d.name} fill={COLORS[i]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="chart-legend">{data.distribution.map((d,i)=><span key={d.name}><i style={{background:COLORS[i]}}/>{d.name}<strong>{d.value}</strong></span>)}</div></>:<p className="empty">Your risk breakdown will appear after your first assessment.</p>}</section><section className="panel"><h2>Application Trend</h2><p className="muted">Applications per day · UTC</p><Trend data={data.trend} field="applications" label="Applications"/></section><section className="panel"><h2>Affordability score Trend</h2><p className="muted">Daily average score · UTC</p><Trend data={data.trend} field="health" label="Affordability score"/></section></div>;
}
function Trend({data,field,label}:{data:ReturnType<typeof dashboardAnalytics>['trend'];field:'applications'|'health';label:string}) {
  if(!data.length)return <p className="empty">Create an application to start tracking your progress.</p>;
  return <><div className="chart" role="img" aria-label={`${label} over ${data.length} day(s)`}><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{top:12,right:18,left:-20,bottom:0}}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0"/><XAxis dataKey="date" tickFormatter={d=>String(d).slice(5)} tick={{fontSize:11}} tickLine={false}/><YAxis domain={field==='health'?[0,100]:[0,'auto']} allowDecimals={field==='health'} tick={{fontSize:11}} tickLine={false}/><Tooltip/><Line type="linear" dataKey={field} name={label} stroke="#0F766E" strokeWidth={3} dot={{r:4,fill:'#14B8A6'}} isAnimationActive={false}/></LineChart></ResponsiveContainer></div><details className="chart-data"><summary>View chart data</summary><table><thead><tr><th>Date</th><th>{label}</th></tr></thead><tbody>{data.map(d=><tr key={d.date}><td>{d.date}</td><td>{d[field]===null?'—':Number(d[field]).toFixed(field==='health'?1:0)}</td></tr>)}</tbody></table></details></>;
}
