import { Application, Result } from "../lib/applications";
import { financialInsights, financialHealth, formatCurrency, riskLevel } from "../lib/finance";

export function RiskBadge({probability}:{probability:number}) {
  const level=riskLevel(probability);
  return <span className={`badge ${level}`}><span aria-hidden="true">{level==="Low"?"●":level==="Moderate"?"●":"●"}</span> {level} Risk</span>;
}
export function EstimateNote() {
  return <p className="estimate-note">Indicative estimates, not a loan offer. ₹ is a display label; amounts are not currency-converted.</p>;
}
export function Assessment({result}:{result:Result}) {
  return <><div className="cards assessment-cards"><div className="card"><span className="muted">Risk Level</span><div className="metric"><RiskBadge probability={result.probability}/></div></div><div className="card"><span className="muted">Financial Health Score</span><strong className="metric">{financialHealth(result.probability).toFixed(1)}<small> / 100</small></strong><div className="score-track"><span style={{width:`${financialHealth(result.probability)}%`}}/></div></div><div className="card"><span className="muted">Risk Probability</span><strong className="metric">{(result.probability*100).toFixed(2)}%</strong></div></div><section className="panel assessment-panel"><div><div className="eyebrow">Assessment Result</div><h2>{riskLevel(result.probability)==="Low"?"A positive starting point":riskLevel(result.probability)==="Moderate"?"A balanced look at your next step":"Plan your next step carefully"}</h2><p>Your risk level reflects your estimated probability. Your Financial Health Score is its inverse on a 0–100 scale.</p></div><RiskBadge probability={result.probability}/></section>{result.quality_flags.length>0&&<div className="notice">Some details fall outside the information this estimate handles best. Treat the result with extra caution.</div>}</>;
}
export function FinancialSummary({application}:{application:Application}) {
  const income=Number(application.input?.annual_income);
  const insight=financialInsights(income, Number(application.requested_amount), application.quote?.term_months??0, application.quote?Number(application.quote.monthly_payment):undefined);
  if(!insight)return <section className="panel"><h2>Financial Summary</h2><p>Income or repayment details are unavailable for this application.</p></section>;
  const fields=[['Annual Income',formatCurrency(income)],['Monthly Income',formatCurrency(insight.monthlyIncome)],['Requested Loan',formatCurrency(insight.principal)],['Estimated EMI',`${formatCurrency(insight.emi)}/month`],['EMI Ratio',`${(insight.ratio*100).toFixed(1)}%`],['Risk Level',application.result?`${riskLevel(application.result.probability)} Risk`:'Unavailable'],['Financial Health Score',application.result?`${financialHealth(application.result.probability).toFixed(1)} / 100`:'Unavailable']];
  return <section className="panel"><div className="section-heading"><h2>Financial Summary</h2><span className="muted">Application {application.id.slice(0,8).toUpperCase()}</span></div><dl className="financial-grid">{fields.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>;
}
export function AffordabilityInsights({application}:{application:Application}) {
  const insight=financialInsights(Number(application.input?.annual_income),Number(application.requested_amount),application.quote?.term_months??0,application.quote?Number(application.quote.monthly_payment):undefined);
  if(!insight)return <section className="panel"><h2>Affordability Assessment</h2><p>Add complete income and term details in a new application to see an estimate.</p></section>;
  return <><section className="panel"><div className="section-heading"><h2>Affordability Assessment</h2><span className={`badge ${insight.assessment==="Comfortable"?"Low":insight.assessment==="Manageable"?"Moderate":"High"}`}>{insight.assessment}</span></div><p>Your estimated EMI uses <strong>{(insight.ratio*100).toFixed(1)}%</strong> of your monthly income.</p><div className="affordability-track"><span style={{width:`${Math.min(insight.ratio*100,100)}%`,background:insight.ratio<.2?'#22C55E':insight.ratio<=.4?'#F59E0B':'#EF4444'}}/></div><div className="scale-labels"><span>Under 20% · Comfortable</span><span>20–40% · Manageable</span><span>Over 40% · Aggressive</span></div><p className="muted">Based on this loan only. Existing EMIs, living expenses and fees are not included.</p></section><section className="panel"><div className="section-heading"><div><h2>Recommended Loan Range</h2><p className="muted">Planning estimates at 12% annual interest over {insight.months} months.</p></div><span className="badge">EMI budget up to {formatCurrency(insight.recommendedMaxEmi)}/month</span></div><div className="loan-ranges">{insight.ranges.map(range=><div className="range-card" key={range.label}><span className="muted">{range.label}</span><strong>{formatCurrency(range.min)} – {formatCurrency(range.max)}</strong><span>{range.lower*100}–{range.upper*100}% of monthly income</span></div>)}</div><p className="muted">These ranges are not an eligibility or affordability guarantee. Choose a lower amount if other commitments reduce your available income.</p></section></>;
}
