"use client";
import { useEffect, useState, FormEvent } from "react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { api, ApiError, User } from "../lib/api";

import { Application, Page, loadApplicationPage } from "../lib/applications";
import { formatCurrency } from "../lib/finance";
import { Assessment, FinancialSummary, AffordabilityInsights, EstimateNote } from "./financial-insights";
import ApplicationTable from "./application-table";
import ConsumerDashboard from "./consumer-dashboard";
import InstallmentWorkspace from './installment-workspace';
import BorrowingPlanner from './borrowing-planner';
import ModelResearchDashboard from './model-research-dashboard';

type Stats = {total_users:number;total_applications:number;total_predictions:number};
const money = formatCurrency;
const date = (value:string) => new Date(value).toLocaleString();
const words = (value:string) => value.toLowerCase().replaceAll("_", " ");
function ErrorBox({message}:{message:string}) { return message ? <div className="error" role="alert">{message}</div> : null; }


function AuthPage({register=false,admin=false}:{register?:boolean;admin?:boolean}) {
 const router=useRouter(); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [done,setDone]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>) { e.preventDefault(); const form=new FormData(e.currentTarget);setBusy(true);setError("");
  try { const body={email:form.get("email"),password:form.get("password"),...(register?{full_name:form.get("full_name")}: {})};
   const response=await api<User>(register?"/auth/register":"/auth/login",{method:"POST",body:JSON.stringify(body)});
   if(register) {setDone(true);return;} if(admin && response.role!=="ADMIN") {await api("/auth/logout",{method:"POST"}); throw new Error("An administrator account is required.");}
   router.replace(response.role==="ADMIN"?"/admin":"/dashboard");
  } catch(e) {setError((e as Error).message);} finally {setBusy(false);}
 }
 return <div className="auth"><aside className="auth-story"><Link className="brand" href="/login">Credit<span>IQ</span></Link><div className="story-copy"><div className="eyebrow" style={{color:"#65d2b6"}}>Clarity before commitment</div><h1>A clearer view of credit risk.</h1><p>Understand your financial health, explore repayment options and make your next step with confidence.</p></div><p>YOUR FINANCES. A CLEARER PICTURE.</p></aside><main className="auth-form"><div className="eyebrow">{admin?"Administrator access":"Your financial workspace"}</div><h1>{register?"Create your account":admin?"Admin sign in":"Welcome back"}</h1><p>{register?"Start exploring your credit profile.":"Sign in to continue to CreditIQ."}</p><ErrorBox message={error}/>{done?<div className="notice">Registration processed. <Link href="/login">Continue to sign in</Link>.</div>:<form onSubmit={submit}>{register&&<label>Full name<input name="full_name" autoComplete="name" required maxLength={200}/></label>}<label>Email address<input type="email" name="email" autoComplete="username" required/></label><label>Password<input type="password" name="password" autoComplete={register?"new-password":"current-password"} minLength={register?15:1} maxLength={128} required/></label>{register&&<p className="muted">Use at least 15 characters.</p>}<button className="btn" disabled={busy}>{busy?"Please wait…":register?"Create account":"Sign in"}</button></form>}<p className="muted">{register?<Link href="/login">Already registered? Sign in</Link>:<Link href="/register">New here? Create an account</Link>}</p><p className="muted"><Link href={admin?"/login":"/admin/login"}>{admin?"User sign in":"Administrator sign in"}</Link></p></main></div>;
}

export default function Workspace() {
 const path=usePathname(); const router=useRouter(); const publicPage=["/","/login","/register","/admin/login"].includes(path); const admin=path.startsWith("/admin");
 const [user,setUser]=useState<User|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(true);
 useEffect(()=>{if(publicPage)return;let active=true;setLoading(true);setError("");api<User>("/me").then(u=>{if(active){setUser(u);if(admin&&u.role!=="ADMIN")router.replace("/dashboard");}}).catch(e=>{if(active){if(e instanceof ApiError&&e.status===401)router.replace(admin?"/admin/login":"/login");else setError(e.message);}}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[path,publicPage,admin,router]);
 if(publicPage)return <AuthPage key={path} register={path==="/register"} admin={path==="/admin/login"}/>;
 if(loading||!user||admin&&user.role!=="ADMIN")return <main className="workspace"><p role="status">{error?"Unable to open workspace.":"Opening your workspace…"}</p><ErrorBox message={error}/><Link href="/login">Return to sign in</Link></main>;
 const links=admin?[["/admin","Overview"],["/admin/users","Users"],["/admin/applications","Applications"],["/admin/statistics","Statistics"],["/admin/installments","Repayment insights"],["/admin/model-research","Model research"]]:[["/dashboard","Dashboard"],["/applications/new","New application"],["/applications","Application history"],["/borrowing-planner","Borrowing Planner"],["/profile","Profile"],["/financial-analysis","Repayment Intelligence"]];
 async function logout(){try{await api("/auth/logout",{method:"POST"});setUser(null);router.replace("/login");}catch(e){setError((e as Error).message);}}
 let content;
 if(path==="/dashboard")content=<ConsumerDashboard user={user}/>;
 else if(path==="/admin/model-research")content=<ModelResearchDashboard/>;
 else if(path==="/applications/new")content=<NewApplication/>;
 else if(path==="/applications"||path==="/admin/applications")content=<Applications admin={admin}/>;
 else if(/^\/(admin\/)?applications\/[^/]+(\/result)?$/.test(path))content=<Details id={path.split("/")[admin?3:2]} admin={admin} resultOnly={path.endsWith("/result")}/>;
 else if(path==="/financial-analysis"||path==="/admin/installments")content=<InstallmentWorkspace admin={admin||user.role==="ADMIN"}/>;
 else if(path==="/borrowing-planner"&&!admin)content=<BorrowingPlanner/>;
 else if(path==="/profile")content=<Profile user={user}/>;
 else if(path==="/admin"||path==="/admin/statistics")content=<Statistics/>;
 else if(path==="/admin/users")content=<Users/>;
 else if(/^\/admin\/users\/[^/]+$/.test(path))content=<UserDetails id={path.split("/")[3]}/>;
 else content=<><h1>Page not found</h1><Link href="/dashboard">Return to dashboard</Link></>;
 return <div className="shell"><aside className="sidebar"><Link href={admin?"/admin":"/dashboard"} className="brand">Credit<span>IQ</span></Link><div className="eyebrow" style={{color:"#9fbfbc"}}>{admin?"Read-only administration":"Personal workspace"}</div><nav>{links.map(([href,label])=><Link className={path===href?"active":""} key={href} href={href}>{label}</Link>)}</nav><div className="footer">Your next step, made clearer.<br/>CreditIQ · Financial insights</div></aside><div className="main"><header className="topbar"><span className="badge">FINANCIAL WORKSPACE</span><div className="flex items-center gap-4"><span className="muted">{user.full_name}</span><button className="btn secondary" onClick={logout}>Sign out</button></div></header><main className="workspace"><ErrorBox message={error}/><div key={path}>{content}</div></main></div></div>;
}

function useLoad<T>(url:string){const [data,setData]=useState<T|null>(null);const [error,setError]=useState("");useEffect(()=>{let active=true;setData(null);setError("");(url.includes("/applications?") ? loadApplicationPage(url,url.startsWith("/admin")) as Promise<T> : api<T>(url)).then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[url]);return {data,error};}
function Title({kicker,title,description}:{kicker:string;title:string;description:string}){return <><div className="eyebrow">{kicker}</div><h1>{title}</h1><p>{description}</p></>;}
function Pagination({total,offset,setOffset}:{total:number;offset:number;setOffset:(n:number)=>void}){return <div className="pagination"><button className="btn secondary" disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-20))}>Previous</button><span className="muted">{total?offset+1:0}–{Math.min(offset+20,total)} of {total}</span><button className="btn secondary" disabled={offset+20>=total} onClick={()=>setOffset(offset+20)}>Next</button></div>;}
function Applications({admin}:{admin:boolean}){const [offset,setOffset]=useState(0);const {data,error}=useLoad<Page<Application>>(`${admin?"/admin":""}/applications?limit=20&offset=${offset}`);return <><Title kicker={admin?"Read only":"Your records"} title="Application history" description={admin?"View submitted applications across the workspace.":"Revisit your submitted details and model estimates."}/><ErrorBox message={error}/><section className="panel">{data?<><ApplicationTable items={data.items} admin={admin}/><Pagination total={data.total} offset={offset} setOffset={setOffset}/></>:!error&&<p role="status">Loading…</p>}</section></>;}
function Details({id,admin,resultOnly}:{id:string;admin:boolean;resultOnly:boolean}){const {data,error}=useLoad<Application>(`${admin?"/admin":""}/applications/${id}`);return <><Title kicker="Application record" title={resultOnly?"Your assessment result":"Application details"} description={`Reference ${id.slice(0,8).toUpperCase()} · saved application`}/><EstimateNote/><ErrorBox message={error}/>{data?<>{data.result&&<><Assessment result={data.result}/><FinancialSummary application={data}/><AffordabilityInsights application={data}/></>}<section className="panel"><h2>Repayment estimate</h2><dl className="detailgrid"><div><dt>Requested amount (₹)</dt><dd>{money(data.requested_amount)}</dd></div><div><dt>Monthly payment</dt><dd>{money(data.quote?.monthly_payment??0)}</dd></div><div><dt>Term</dt><dd>{data.quote?.term_months} months</dd></div><div><dt>Estimated annual rate</dt><dd>12% · excluding fees</dd></div></dl></section>{!resultOnly&&<section className="panel"><h2>Submitted information</h2><dl className="detailgrid">{Object.entries(data.input??{}).filter(([k])=>k!=="research_acknowledged").map(([k,v])=><div key={k}><dt className="capitalize">{words(k)}</dt><dd>{v===null?"Not reported":["annual_income","requested_amount"].includes(k)?formatCurrency(String(v)):String(v).replaceAll("_"," ")}</dd></div>)}</dl></section>}{!admin&&<><Link className="btn secondary" href={resultOnly?`/applications/${id}`:`/applications/${id}/result`}>{resultOnly?"Application details":"Open assessment result"}</Link><History id={id}/></>}</>:!error&&<p role="status">Loading record…</p>}</>;}
function History({id}:{id:string}){const {data,error}=useLoad<{id:string;event_type:string;created_at:string}[]>(`/applications/${id}/history`);return <section className="panel"><h2>Application timeline</h2><ErrorBox message={error}/>{data?.map(e=><div key={e.id}><strong className="capitalize">{e.event_type==="RESEARCH_SCORED"?"Assessment completed":words(e.event_type)}</strong><p>{date(e.created_at)}</p></div>)}</section>;}
function Profile({user}:{user:User}){return <><Title kicker="Your account" title="Profile" description="Your identity and workspace access."/><section className="panel"><dl className="detailgrid"><div><dt>Name</dt><dd>{user.full_name}</dd></div><div><dt>Email</dt><dd>{user.email}</dd></div><div><dt>Role</dt><dd>{user.role}</dd></div><div><dt>Account ID</dt><dd>{user.id}</dd></div></dl></section><EstimateNote/></>;}
function Statistics(){const {data,error}=useLoad<Stats>("/admin/statistics");return <><Title kicker="Read-only administration" title="Workspace statistics" description="Counts from persisted records. No lending decisions or overrides are available."/><EstimateNote/><ErrorBox message={error}/><div className="cards">{[["Total users",data?.total_users],["Total applications",data?.total_applications],["Total predictions",data?.total_predictions]].map(([label,value])=><div className="card" key={label}><span className="muted">{label}</span><strong className="metric">{value??"—"}</strong></div>)}</div></>;}
function Users(){const [offset,setOffset]=useState(0);const {data,error}=useLoad<Page<User>>(`/admin/users?limit=20&offset=${offset}`);return <><Title kicker="Read only" title="Workspace users" description="View registered users and their assigned roles."/><ErrorBox message={error}/><section className="panel">{data?<><div className="tablewrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th></tr></thead><tbody>{data.items.map(u=><tr key={u.id}><td><Link href={`/admin/users/${u.id}`}>{u.full_name}</Link></td><td>{u.email}</td><td><span className="badge">{u.role}</span></td></tr>)}</tbody></table></div><Pagination total={data.total} offset={offset} setOffset={setOffset}/></>:!error&&<p role="status">Loading users…</p>}</section></>;}
function UserDetails({id}:{id:string}){const {data,error}=useLoad<User>(`/admin/users/${id}`);return <><ErrorBox message={error}/>{data?<Profile user={data}/>:!error&&<p role="status">Loading user…</p>}</>;}

const employment=["WORKING","COMMERCIAL_ASSOCIATE","STATE_SERVANT","PENSIONER","UNEMPLOYED","STUDENT","BUSINESSMAN","MATERNITY_LEAVE","OTHER"];
const education=["LOWER_SECONDARY","SECONDARY","INCOMPLETE_HIGHER","HIGHER","ACADEMIC_DEGREE","OTHER"];
const occupations=["LABORER","CORE_STAFF","ACCOUNTANT","MANAGER","DRIVER","SALES","CLEANING","COOKING","PRIVATE_SERVICE","MEDICAL","SECURITY","HIGH_TECH","WAITING_BAR","LOW_SKILL_LABOR","REALTY_AGENT","SECRETARY","IT","HR","OTHER"];
const housing=["OWN_OR_APARTMENT","WITH_PARENTS","RENTED","MUNICIPAL","OFFICE","COOPERATIVE","OTHER"];
function Select({label,name,values,optional=false}:{label:string;name:string;values:string[];optional?:boolean}){return <div className="grid gap-2"><label htmlFor={name}>{label}</label><select id={name} name={name} required={!optional} defaultValue=""><option value="">{optional?"Not reported":"Select an option"}</option>{values.map(v=><option key={v} value={v}>{words(v)}</option>)}</select></div>;}
function NewApplication(){const router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [retry,setRetry]=useState<{body:string;key:string}|null>(null);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);const numeric=["age_years","years_employed","household_size","dependent_children","term_months"];const b:Record<string,unknown>={};f.forEach((value,key)=>{b[key]=numeric.includes(key)?value===""?null:Number(value):value;});b.research_acknowledged=f.get("research_acknowledged")==="on";b.occupation=b.occupation||null;b.housing_status=b.housing_status||null;const body=JSON.stringify(b);const key=retry?.body===body?retry.key:crypto.randomUUID();setRetry({body,key});try{const result=await api<Application>("/applications",{method:"POST",body,headers:{"Idempotency-Key":key}});router.push(`/applications/${result.id}/result`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><Title kicker="Your next step" title="New application" description="Tell us about your income and loan needs to explore your financial outlook."/><EstimateNote/><form onSubmit={submit}><section className="panel"><h2>About you</h2><div className="formgrid"><label>Age (years)<input name="age_years" type="number" min={18} max={100} required/></label><Select name="employment_type" label="Employment type" values={employment}/><label>Years in current employment (blank if unknown)<input name="years_employed" type="number" min={0} max={100} step="0.1"/></label><label>Annual income (₹)<input name="annual_income" type="number" min="0.01" max="100000000" step="0.01" required/></label><Select name="education_level" label="Education" values={education}/><label>Household members, including you<input name="household_size" type="number" min={1} max={30} required/></label><label>Dependent children<input name="dependent_children" type="number" min={0} max={29} required/></label><Select name="occupation" label="Occupation (optional)" values={occupations} optional/><Select name="housing_status" label="Housing (optional)" values={housing} optional/></div></section><section className="panel"><h2>Your loan preferences</h2><div className="formgrid"><label>Requested amount (₹)<input name="requested_amount" type="number" min={1000} max={10000000} step="0.01" required/></label><label>Term (months)<input name="term_months" type="number" min={6} max={120} required/></label></div><p className="muted">Your estimated monthly payment uses 12% annual interest and excludes fees.</p><label className="check"><input type="checkbox" name="research_acknowledged" required/><span>I understand these estimates use the information I provide and do not guarantee a loan offer.</span></label><ErrorBox message={error}/><button className="btn" disabled={busy}>{busy?"Preparing your assessment…":"Get my assessment"}</button></section></form></>;
}

