"""initial research schema

Revision ID: 20261003_0001
Revises: 
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '20261003_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('release_name', sa.Text(), nullable=False),
    sa.Column('variant', sa.Text(), nullable=False),
    sa.Column('feature_schema_version', sa.Text(), nullable=False),
    sa.Column('target_definition_version', sa.Text(), nullable=False),
    sa.Column('training_manifest_key', sa.Text(), nullable=False),
    sa.Column('artifact_key', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('calibration_version', sa.Text(), nullable=False),
    sa.Column('runtime_lock_hash', sa.String(length=64), nullable=False),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('lifecycle_status', sa.Text(), server_default='REGISTERED', nullable=False),
    sa.Column('mode', sa.Text(), server_default='RESEARCH_ONLY', nullable=False),
    sa.Column('release_ready', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(metrics_json) = 'object'", name=op.f('ck_model_versions_metrics_json_shape')),
    sa.CheckConstraint("lifecycle_status IN ('REGISTERED', 'VALIDATED', 'RETIRED')", name=op.f('ck_model_versions_lifecycle_status_values')),
    sa.CheckConstraint("mode IN ('RESEARCH_ONLY')", name=op.f('ck_model_versions_mode_values')),
    sa.CheckConstraint("runtime_lock_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_model_versions_runtime_lock_hash_sha256')),
    sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_model_versions_sha256_sha256')),
    sa.CheckConstraint("variant IN ('LITE', 'FULL')", name=op.f('ck_model_versions_variant_values')),
    sa.CheckConstraint('release_ready = false', name=op.f('ck_model_versions_research_release')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions')),
    sa.UniqueConstraint('id', 'variant', name=op.f('uq_model_versions_id_variant')),
    sa.UniqueConstraint('release_name', name=op.f('uq_model_versions_release_name'))
    )
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload_reference', sa.Text(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_outbox_events_attempt_nonnegative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events'))
    )
    op.create_index('ix_outbox_pending_created', 'outbox_events', ['created_at'], unique=False, postgresql_where=sa.text('dispatched_at IS NULL'))
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('normalized_email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), server_default='USER', nullable=False),
    sa.Column('account_status', sa.Text(), server_default='ACTIVE', nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("account_status IN ('ACTIVE', 'DISABLED', 'CLOSED')", name=op.f('ck_users_account_status_values')),
    sa.CheckConstraint("jsonb_typeof(permissions) = 'array'", name=op.f('ck_users_permissions_shape')),
    sa.CheckConstraint("normalized_email = lower(btrim(normalized_email)) AND position('@' in normalized_email) > 1", name=op.f('ck_users_normalized_email_format')),
    sa.CheckConstraint("role IN ('USER', 'ADMIN')", name=op.f('ck_users_role_values')),
    sa.CheckConstraint('length(password_hash) > 0', name=op.f('ck_users_password_hash_nonempty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('normalized_email', name=op.f('uq_users_normalized_email'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=False),
    sa.Column('redacted_metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("jsonb_typeof(redacted_metadata_json) = 'object'", name=op.f('ck_audit_events_redacted_metadata_json_shape')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_events_actor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_table('auth_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hashed_refresh_token', sa.Text(), nullable=False),
    sa.Column('token_family_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_auth_sessions_expires_after_creation')),
    sa.CheckConstraint('revoked_at IS NULL OR revoked_at >= created_at', name=op.f('ck_auth_sessions_revocation_time')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions')),
    sa.UniqueConstraint('hashed_refresh_token', name=op.f('uq_auth_sessions_hashed_refresh_token'))
    )
    op.create_index('ix_auth_sessions_user_id', 'auth_sessions', ['user_id'], unique=False)
    op.create_table('loan_applications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('product_code', sa.Text(), server_default='CASH_INSTALLMENT_V1', nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('requested_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('workflow_status', sa.Text(), server_default='DRAFT', nullable=False),
    sa.Column('current_decision_id', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_loan_applications_currency_format')),
    sa.CheckConstraint("product_code IN ('CASH_INSTALLMENT_V1')", name=op.f('ck_loan_applications_product_code_values')),
    sa.CheckConstraint("requested_amount > 0 AND requested_amount < 'Infinity'", name=op.f('ck_loan_applications_requested_amount_finite')),
    sa.CheckConstraint("workflow_status IN ('DRAFT', 'SUBMITTED', 'PROCESSING', 'PENDING_DATA', 'MANUAL_REVIEW', 'DECIDED', 'WITHDRAWN')", name=op.f('ck_loan_applications_workflow_status_values')),
    sa.CheckConstraint('current_version > 0', name=op.f('ck_loan_applications_current_version_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_loan_applications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loan_applications')),
    sa.UniqueConstraint('id', 'user_id', name=op.f('uq_loan_applications_id_user_id'))
    )
    op.create_index('ix_applications_status_submitted', 'loan_applications', ['workflow_status', 'submitted_at'], unique=False)
    op.create_index('ix_applications_user_created', 'loan_applications', ['user_id', 'created_at'], unique=False)
    op.create_table('model_deployments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_code', sa.Text(), nullable=False),
    sa.Column('variant', sa.Text(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("variant IN ('LITE', 'FULL')", name=op.f('ck_model_deployments_variant_values')),
    sa.CheckConstraint('retired_at IS NULL OR retired_at >= activated_at', name=op.f('ck_model_deployments_retirement_order')),
    sa.ForeignKeyConstraint(['model_version_id', 'variant'], ['model_versions.id', 'model_versions.variant'], name=op.f('fk_model_deployments_model_version_id_model_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_deployments'))
    )
    op.create_index('uq_model_deployment_active', 'model_deployments', ['product_code', 'variant'], unique=True, postgresql_where=sa.text('retired_at IS NULL'))
    op.create_table('policy_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('product_code', sa.Text(), nullable=False),
    sa.Column('variant', sa.Text(), nullable=False),
    sa.Column('mode', sa.Text(), server_default='SANDBOX', nullable=False),
    sa.Column('approve_below', sa.Double(), nullable=True),
    sa.Column('reject_at', sa.Double(), nullable=True),
    sa.Column('band_thresholds_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('affordability_rules_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('validation_report_key', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("jsonb_typeof(affordability_rules_json) = 'object'", name=op.f('ck_policy_versions_affordability_rules_json_shape')),
    sa.CheckConstraint("jsonb_typeof(band_thresholds_json) = 'object'", name=op.f('ck_policy_versions_band_thresholds_json_shape')),
    sa.CheckConstraint("mode IN ('SANDBOX', 'SHADOW')", name=op.f('ck_policy_versions_mode_values')),
    sa.CheckConstraint("variant IN ('LITE', 'FULL')", name=op.f('ck_policy_versions_variant_values')),
    sa.CheckConstraint('(approve_below IS NULL AND reject_at IS NULL) OR (approve_below IS NOT NULL AND reject_at IS NOT NULL AND 0 < approve_below AND approve_below < reject_at AND reject_at < 1)', name=op.f('ck_policy_versions_threshold_order')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_policy_versions_approved_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_versions')),
    sa.UniqueConstraint('version', name=op.f('uq_policy_versions_version'))
    )
    op.create_table('user_profiles',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('contact_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(contact_json) = 'object'", name=op.f('ck_user_profiles_contact_json_shape')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_profiles'))
    )
    op.create_table('application_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('input_schema_version', sa.Text(), nullable=False),
    sa.Column('immutable_input_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.CheckConstraint("input_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_application_versions_input_hash_sha256')),
    sa.CheckConstraint("jsonb_typeof(immutable_input_json) = 'object'", name=op.f('ck_application_versions_immutable_input_json_shape')),
    sa.CheckConstraint('version > 0', name=op.f('ck_application_versions_version_positive')),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], name=op.f('fk_application_versions_application_id_loan_applications')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_application_versions_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_versions')),
    sa.UniqueConstraint('application_id', 'version', name=op.f('uq_application_versions_application_id_version')),
    sa.UniqueConstraint('id', 'application_id', 'version', name=op.f('uq_application_versions_id_application_id_version')),
    sa.UniqueConstraint('id', 'application_id', name=op.f('uq_application_versions_id_application_id'))
    )
    op.create_table('data_consents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('source_scope', sa.Text(), nullable=False),
    sa.Column('consent_version', sa.Text(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('revoked_at IS NULL OR revoked_at >= granted_at', name=op.f('ck_data_consents_revocation_order')),
    sa.ForeignKeyConstraint(['application_id', 'user_id'], ['loan_applications.id', 'loan_applications.user_id'], name=op.f('fk_data_consents_application_id_loan_applications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_consents')),
    sa.UniqueConstraint('id', 'application_id', name=op.f('uq_data_consents_id_application_id'))
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.Text(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('filter_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.Text(), server_default='QUEUED', nullable=False),
    sa.Column('object_key', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("content_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_reports_content_hash_sha256')),
    sa.CheckConstraint("format IN ('PDF', 'XLSX')", name=op.f('ck_reports_format_values')),
    sa.CheckConstraint("jsonb_typeof(filter_snapshot_json) = 'object'", name=op.f('ck_reports_filter_snapshot_json_shape')),
    sa.CheckConstraint("status <> 'SUCCEEDED' OR (object_key IS NOT NULL AND content_hash IS NOT NULL AND completed_at IS NOT NULL)", name=op.f('ck_reports_completed_report_object')),
    sa.CheckConstraint("status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'EXPIRED')", name=op.f('ck_reports_status_values')),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], name=op.f('fk_reports_application_id_loan_applications')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_reports_requested_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index('ix_reports_requester_created', 'reports', ['requested_by', 'created_at'], unique=False)
    op.create_table('feature_snapshots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('application_version_id', sa.UUID(), nullable=False),
    sa.Column('variant', sa.Text(), nullable=False),
    sa.Column('feature_schema_version', sa.Text(), nullable=False),
    sa.Column('feature_values_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('ordered_feature_hash', sa.String(length=64), nullable=False),
    sa.Column('quality_flags_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("jsonb_typeof(feature_values_json) = 'object'", name=op.f('ck_feature_snapshots_feature_values_json_shape')),
    sa.CheckConstraint("jsonb_typeof(quality_flags_json) = 'array'", name=op.f('ck_feature_snapshots_quality_flags_json_shape')),
    sa.CheckConstraint("ordered_feature_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_feature_snapshots_ordered_feature_hash_sha256')),
    sa.CheckConstraint("variant IN ('LITE', 'FULL')", name=op.f('ck_feature_snapshots_variant_values')),
    sa.ForeignKeyConstraint(['application_version_id'], ['application_versions.id'], name=op.f('fk_feature_snapshots_application_version_id_application_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_snapshots')),
    sa.UniqueConstraint('id', 'application_version_id', 'variant', name=op.f('uq_feature_snapshots_id_application_version_id_variant')),
    sa.UniqueConstraint('id', 'application_version_id', name=op.f('uq_feature_snapshots_id_application_version_id'))
    )
    op.create_table('loan_quotes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('application_version_id', sa.UUID(), nullable=False),
    sa.Column('product_version', sa.Text(), nullable=False),
    sa.Column('principal', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('annual_rate', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('monthly_payment', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('fees_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("annual_rate >= 0 AND annual_rate < 'Infinity'", name=op.f('ck_loan_quotes_annual_rate_finite')),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_loan_quotes_currency_format')),
    sa.CheckConstraint("jsonb_typeof(fees_json) = 'object'", name=op.f('ck_loan_quotes_fees_json_shape')),
    sa.CheckConstraint("monthly_payment > 0 AND monthly_payment < 'Infinity'", name=op.f('ck_loan_quotes_monthly_payment_finite')),
    sa.CheckConstraint("principal > 0 AND principal < 'Infinity'", name=op.f('ck_loan_quotes_principal_finite')),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_loan_quotes_expiry')),
    sa.CheckConstraint('term_months > 0', name=op.f('ck_loan_quotes_term_positive')),
    sa.ForeignKeyConstraint(['application_version_id'], ['application_versions.id'], name=op.f('fk_loan_quotes_application_version_id_application_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loan_quotes'))
    )
    op.create_index('ix_loan_quotes_application_version', 'loan_quotes', ['application_version_id'], unique=False)
    op.create_table('scoring_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('application_version_id', sa.UUID(), nullable=False),
    sa.Column('variant_requested', sa.Text(), server_default='AUTO', nullable=False),
    sa.Column('status', sa.Text(), server_default='QUEUED', nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('request_body_hash', sa.String(length=64), nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("request_body_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_scoring_jobs_request_body_hash_sha256')),
    sa.CheckConstraint("status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'PENDING_DATA')", name=op.f('ck_scoring_jobs_status_values')),
    sa.CheckConstraint("variant_requested IN ('AUTO', 'LITE', 'FULL')", name=op.f('ck_scoring_jobs_variant_requested_values')),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_scoring_jobs_attempts_nonnegative')),
    sa.ForeignKeyConstraint(['application_version_id'], ['application_versions.id'], name=op.f('fk_scoring_jobs_application_version_id_application_versions')),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_scoring_jobs_model_version_id_model_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scoring_jobs')),
    sa.UniqueConstraint('application_version_id', 'idempotency_key', name=op.f('uq_scoring_jobs_application_version_id_idempotency_key')),
    sa.UniqueConstraint('id', 'application_version_id', 'model_version_id', name=op.f('uq_scoring_jobs_id_application_version_id_model_version_id'))
    )
    op.create_index('ix_jobs_status_created', 'scoring_jobs', ['status', 'created_at'], unique=False)
    op.create_table('source_snapshots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('application_version_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('source_as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('schema_version', sa.Text(), nullable=False),
    sa.Column('coverage_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('consent_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("content_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_source_snapshots_content_hash_sha256')),
    sa.CheckConstraint("jsonb_typeof(coverage_json) = 'object'", name=op.f('ck_source_snapshots_coverage_json_shape')),
    sa.CheckConstraint("state IN ('COMPLETE', 'CONFIRMED_EMPTY', 'UNAVAILABLE', 'INVALID')", name=op.f('ck_source_snapshots_state_values')),
    sa.CheckConstraint('source_as_of <= fetched_at', name=op.f('ck_source_snapshots_coverage_time')),
    sa.ForeignKeyConstraint(['application_version_id', 'application_id'], ['application_versions.id', 'application_versions.application_id'], name=op.f('fk_source_snapshots_application_version_id_application_versions')),
    sa.ForeignKeyConstraint(['consent_id', 'application_id'], ['data_consents.id', 'data_consents.application_id'], name=op.f('fk_source_snapshots_consent_id_data_consents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_snapshots')),
    sa.UniqueConstraint('id', 'application_id', name=op.f('uq_source_snapshots_id_application_id')),
    sa.UniqueConstraint('id', 'application_version_id', name=op.f('uq_source_snapshots_id_application_version_id'))
    )
    op.create_table('feature_snapshot_sources',
    sa.Column('feature_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('source_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('application_version_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['feature_snapshot_id', 'application_version_id'], ['feature_snapshots.id', 'feature_snapshots.application_version_id'], name=op.f('fk_feature_snapshot_sources_feature_snapshot_id_feature_snapshots')),
    sa.ForeignKeyConstraint(['source_snapshot_id', 'application_version_id'], ['source_snapshots.id', 'source_snapshots.application_version_id'], name=op.f('fk_feature_snapshot_sources_source_snapshot_id_source_snapshots')),
    sa.PrimaryKeyConstraint('feature_snapshot_id', 'source_snapshot_id', name=op.f('pk_feature_snapshot_sources'))
    )
    op.create_table('loan_outcomes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('outcome_definition_version', sa.Text(), nullable=False),
    sa.Column('observation_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome_matured', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('default_observed', sa.Boolean(), nullable=True),
    sa.Column('exposure', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('loss_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('source_snapshot_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("exposure >= 0 AND exposure < 'Infinity'", name=op.f('ck_loan_outcomes_exposure_finite')),
    sa.CheckConstraint("loss_amount >= 0 AND loss_amount < 'Infinity'", name=op.f('ck_loan_outcomes_loss_amount_finite')),
    sa.CheckConstraint('(outcome_matured AND default_observed IS NOT NULL) OR (NOT outcome_matured AND default_observed IS NULL)', name=op.f('ck_loan_outcomes_matured_outcome')),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], name=op.f('fk_loan_outcomes_application_id_loan_applications')),
    sa.ForeignKeyConstraint(['source_snapshot_id', 'application_id'], ['source_snapshots.id', 'source_snapshots.application_id'], name=op.f('fk_loan_outcomes_source_snapshot_id_source_snapshots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loan_outcomes'))
    )
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scoring_job_id', sa.UUID(), nullable=False),
    sa.Column('application_version_id', sa.UUID(), nullable=False),
    sa.Column('feature_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('variant', sa.Text(), nullable=False),
    sa.Column('raw_positive_output', sa.Double(), nullable=False),
    sa.Column('calibrated_pd', sa.Double(), nullable=False),
    sa.Column('quality_flags_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('verification_status', sa.Text(), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("jsonb_typeof(quality_flags_json) = 'array'", name=op.f('ck_predictions_quality_flags_json_shape')),
    sa.CheckConstraint("raw_positive_output > '-Infinity'::float8 AND raw_positive_output < 'Infinity'::float8", name=op.f('ck_predictions_raw_output_finite')),
    sa.CheckConstraint("variant IN ('LITE', 'FULL')", name=op.f('ck_predictions_variant_values')),
    sa.CheckConstraint("verification_status IN ('UNVERIFIED', 'PARTIAL', 'VERIFIED')", name=op.f('ck_predictions_verification_status_values')),
    sa.CheckConstraint('calibrated_pd >= 0 AND calibrated_pd <= 1', name=op.f('ck_predictions_calibrated_pd_bounds')),
    sa.ForeignKeyConstraint(['feature_snapshot_id', 'application_version_id', 'variant'], ['feature_snapshots.id', 'feature_snapshots.application_version_id', 'feature_snapshots.variant'], name=op.f('fk_predictions_feature_snapshot_id_feature_snapshots')),
    sa.ForeignKeyConstraint(['model_version_id', 'variant'], ['model_versions.id', 'model_versions.variant'], name=op.f('fk_predictions_model_version_id_model_versions')),
    sa.ForeignKeyConstraint(['scoring_job_id', 'application_version_id', 'model_version_id'], ['scoring_jobs.id', 'scoring_jobs.application_version_id', 'scoring_jobs.model_version_id'], name=op.f('fk_predictions_scoring_job_id_scoring_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions')),
    sa.UniqueConstraint('id', 'application_version_id', name=op.f('uq_predictions_id_application_version_id')),
    sa.UniqueConstraint('scoring_job_id', name=op.f('uq_predictions_scoring_job_id'))
    )
    op.create_index('ix_predictions_version_scored', 'predictions', ['application_version_id', 'scored_at'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('application_version_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('application_version_number', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=True),
    sa.Column('policy_version_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('reason_codes_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('affordability_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('supersedes_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("(kind = 'RECOMMENDATION' AND status IN ('APPROVAL_CANDIDATE','REJECTION_CANDIDATE','MANUAL_REVIEW','PENDING_DATA')) OR (kind = 'FINAL' AND status IN ('MANUAL_REVIEW','PENDING_DATA','APPROVED','REJECTED'))", name=op.f('ck_decisions_kind_status')),
    sa.CheckConstraint("jsonb_typeof(affordability_snapshot_json) = 'object'", name=op.f('ck_decisions_affordability_snapshot_json_shape')),
    sa.CheckConstraint("jsonb_typeof(reason_codes_json) = 'array'", name=op.f('ck_decisions_reason_codes_json_shape')),
    sa.CheckConstraint("kind IN ('RECOMMENDATION', 'FINAL')", name=op.f('ck_decisions_kind_values')),
    sa.CheckConstraint("status NOT IN ('APPROVED','REJECTED') OR actor_id IS NOT NULL", name=op.f('ck_decisions_human_final_credit_decision')),
    sa.CheckConstraint('supersedes_id IS NULL OR supersedes_id <> id', name=op.f('ck_decisions_no_self_supersede')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_decisions_actor_id_users')),
    sa.ForeignKeyConstraint(['application_version_id', 'application_id', 'application_version_number'], ['application_versions.id', 'application_versions.application_id', 'application_versions.version'], name=op.f('fk_decisions_application_version_id_application_versions')),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], name=op.f('fk_decisions_policy_version_id_policy_versions')),
    sa.ForeignKeyConstraint(['prediction_id', 'application_version_id'], ['predictions.id', 'predictions.application_version_id'], name=op.f('fk_decisions_prediction_id_predictions')),
    sa.ForeignKeyConstraint(['supersedes_id', 'application_version_id'], ['decisions.id', 'decisions.application_version_id'], name=op.f('fk_decisions_supersedes_id_decisions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions')),
    sa.UniqueConstraint('id', 'application_id', 'application_version_number', name=op.f('uq_decisions_id_application_id_application_version_number')),
    sa.UniqueConstraint('id', 'application_id', name=op.f('uq_decisions_id_application_id')),
    sa.UniqueConstraint('id', 'application_version_id', name=op.f('uq_decisions_id_application_version_id'))
    )
    op.create_table('explanations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('explainer_version', sa.Text(), nullable=False),
    sa.Column('explained_output', sa.Text(), nullable=True),
    sa.Column('reference_version', sa.Text(), nullable=True),
    sa.Column('base_value', sa.Double(), nullable=True),
    sa.Column('contributions_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('remainder_value', sa.Double(), nullable=True),
    sa.Column('additivity_error', sa.Double(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.CheckConstraint("additivity_error > '-Infinity'::float8 AND additivity_error < 'Infinity'::float8", name=op.f('ck_explanations_additivity_error_finite')),
    sa.CheckConstraint("base_value > '-Infinity'::float8 AND base_value < 'Infinity'::float8", name=op.f('ck_explanations_base_value_finite')),
    sa.CheckConstraint("explained_output IN ('raw_margin', 'uncalibrated_probability')", name=op.f('ck_explanations_explained_output_values')),
    sa.CheckConstraint("jsonb_typeof(contributions_json) = 'object'", name=op.f('ck_explanations_contributions_json_shape')),
    sa.CheckConstraint("remainder_value > '-Infinity'::float8 AND remainder_value < 'Infinity'::float8", name=op.f('ck_explanations_remainder_value_finite')),
    sa.CheckConstraint("status <> 'SUCCEEDED' OR (explained_output IS NOT NULL AND reference_version IS NOT NULL AND base_value IS NOT NULL AND remainder_value IS NOT NULL AND additivity_error IS NOT NULL)", name=op.f('ck_explanations_success_requires_values')),
    sa.CheckConstraint("status IN ('PENDING', 'SUCCEEDED', 'FAILED')", name=op.f('ck_explanations_status_values')),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], name=op.f('fk_explanations_prediction_id_predictions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_explanations')),
    sa.UniqueConstraint('prediction_id', 'explainer_version', name=op.f('uq_explanations_prediction_id_explainer_version'))
    )
    op.create_table('risk_scores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('score_policy_version', sa.Text(), nullable=False),
    sa.Column('risk_score', sa.Double(), nullable=False),
    sa.Column('risk_band', sa.Text(), nullable=False),
    sa.Column('reference_percentile', sa.Double(), nullable=True),
    sa.Column('reference_cohort_version', sa.Text(), nullable=True),
    sa.Column('credit_health_index', sa.Double(), nullable=False),
    sa.CheckConstraint("risk_band IN ('Low', 'Medium', 'High')", name=op.f('ck_risk_scores_risk_band_values')),
    sa.CheckConstraint('(reference_percentile IS NULL) = (reference_cohort_version IS NULL)', name=op.f('ck_risk_scores_reference_pair')),
    sa.CheckConstraint('credit_health_index >= 0 AND credit_health_index <= 100', name=op.f('ck_risk_scores_credit_health_index_bounds')),
    sa.CheckConstraint('reference_percentile >= 0 AND reference_percentile <= 100', name=op.f('ck_risk_scores_reference_percentile_bounds')),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 100', name=op.f('ck_risk_scores_risk_score_bounds')),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], name=op.f('fk_risk_scores_prediction_id_predictions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_scores')),
    sa.UniqueConstraint('prediction_id', 'score_policy_version', name=op.f('uq_risk_scores_prediction_id_score_policy_version'))
    )
    op.create_table('segment_assignments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('segmenter_version', sa.Text(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('distance', sa.Double(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.CheckConstraint("distance >= 0 AND distance < 'Infinity'", name=op.f('ck_segment_assignments_distance_finite')),
    sa.CheckConstraint("status <> 'ASSIGNED' OR (segment_id IS NOT NULL AND label IS NOT NULL AND distance IS NOT NULL)", name=op.f('ck_segment_assignments_assignment_requires_values')),
    sa.CheckConstraint("status IN ('ASSIGNED', 'UNSUPPORTED')", name=op.f('ck_segment_assignments_status_values')),
    sa.CheckConstraint('segment_id >= 0', name=op.f('ck_segment_assignments_segment_id_nonnegative')),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], name=op.f('fk_segment_assignments_prediction_id_predictions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_segment_assignments')),
    sa.UniqueConstraint('prediction_id', 'segmenter_version', name=op.f('uq_segment_assignments_prediction_id_segmenter_version'))
    )
    op.create_table('application_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('application_version_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('old_status', sa.Text(), nullable=True),
    sa.Column('new_status', sa.Text(), nullable=True),
    sa.Column('decision_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.Text(), nullable=False),
    sa.Column('redacted_event_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("jsonb_typeof(redacted_event_json) = 'object'", name=op.f('ck_application_history_redacted_event_json_shape')),
    sa.CheckConstraint('decision_id IS NULL OR application_version_id IS NOT NULL', name=op.f('ck_application_history_decision_requires_version')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_application_history_actor_id_users')),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], name=op.f('fk_application_history_application_id_loan_applications')),
    sa.ForeignKeyConstraint(['application_version_id', 'application_id'], ['application_versions.id', 'application_versions.application_id'], name=op.f('fk_application_history_application_version_id_application_versions')),
    sa.ForeignKeyConstraint(['decision_id', 'application_version_id'], ['decisions.id', 'decisions.application_version_id'], name=op.f('fk_application_history_decision_id_decisions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_history'))
    )
    op.create_index('ix_history_application_created', 'application_history', ['application_id', 'created_at'], unique=False)
    # Circular references are installed only after all target tables exist.
    op.create_foreign_key('fk_application_current_version', 'loan_applications', 'application_versions',
                          ['id', 'current_version'], ['application_id', 'version'], deferrable=True, initially='DEFERRED')
    op.create_foreign_key('fk_application_current_decision', 'loan_applications', 'decisions',
                          ['current_decision_id', 'id', 'current_version'],
                          ['id', 'application_id', 'application_version_number'], deferrable=True, initially='DEFERRED')
    op.execute("""CREATE FUNCTION creditiq_reject_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN RAISE EXCEPTION 'immutable record in %', TG_TABLE_NAME USING ERRCODE = '23514'; END; $$""")
    op.execute("CREATE TRIGGER immutable_record BEFORE UPDATE OR DELETE ON application_versions FOR EACH ROW EXECUTE FUNCTION creditiq_reject_mutation()")
    op.execute("CREATE TRIGGER immutable_record BEFORE UPDATE OR DELETE ON loan_quotes FOR EACH ROW EXECUTE FUNCTION creditiq_reject_mutation()")
    op.execute("CREATE TRIGGER immutable_record BEFORE UPDATE OR DELETE ON source_snapshots FOR EACH ROW EXECUTE FUNCTION creditiq_reject_mutation()")
    op.execute("CREATE TRIGGER immutable_record BEFORE UPDATE OR DELETE ON feature_snapshots FOR EACH ROW EXECUTE FUNCTION creditiq_reject_mutation()")
    op.execute("CREATE TRIGGER immutable_record BEFORE UPDATE OR DELETE ON feature_snapshot_sources FOR EACH ROW EXECUTE FUNCTION creditiq_reject_mutation()")
    op.execute("CREATE TRIGGER immutable_record BEFORE UPDATE OR DELETE ON model_versions FOR EACH ROW EXECUTE FUNCTION creditiq_reject_mutation()")
    op.execute("CREATE TRIGGER immutable_record BEFORE UPDATE OR DELETE ON predictions FOR EACH ROW EXECUTE FUNCTION creditiq_reject_mutation()")
    op.execute("CREATE TRIGGER immutable_record BEFORE UPDATE OR DELETE ON risk_scores FOR EACH ROW EXECUTE FUNCTION creditiq_reject_mutation()")
    op.execute("CREATE TRIGGER immutable_record BEFORE UPDATE OR DELETE ON policy_versions FOR EACH ROW EXECUTE FUNCTION creditiq_reject_mutation()")
    op.execute("CREATE TRIGGER immutable_record BEFORE UPDATE OR DELETE ON decisions FOR EACH ROW EXECUTE FUNCTION creditiq_reject_mutation()")
    op.execute("CREATE TRIGGER immutable_record BEFORE UPDATE OR DELETE ON segment_assignments FOR EACH ROW EXECUTE FUNCTION creditiq_reject_mutation()")
    op.execute("CREATE TRIGGER immutable_record BEFORE UPDATE OR DELETE ON application_history FOR EACH ROW EXECUTE FUNCTION creditiq_reject_mutation()")
    op.execute("CREATE TRIGGER immutable_record BEFORE UPDATE OR DELETE ON loan_outcomes FOR EACH ROW EXECUTE FUNCTION creditiq_reject_mutation()")
    op.execute("CREATE TRIGGER immutable_record BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION creditiq_reject_mutation()")
    op.execute("""CREATE FUNCTION creditiq_protect_explanation() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF OLD.status = 'SUCCEEDED' THEN
        RAISE EXCEPTION 'completed explanation is immutable' USING ERRCODE = '23514';
      END IF;
      IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
      RETURN NEW;
    END; $$""")
    op.execute("CREATE TRIGGER completed_explanation BEFORE UPDATE OR DELETE ON explanations FOR EACH ROW EXECUTE FUNCTION creditiq_protect_explanation()")
    op.execute("""CREATE FUNCTION creditiq_touch_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN NEW.updated_at = now(); RETURN NEW; END; $$""")
    for table_name in ('users', 'user_profiles', 'loan_applications'):
        op.execute(f"CREATE TRIGGER touch_updated_at BEFORE UPDATE ON {table_name} FOR EACH ROW EXECUTE FUNCTION creditiq_touch_updated_at()")
    # ### end Alembic commands ###


def downgrade() -> None:
    # Remove circular references before reverse dependency-order table drops.
    op.drop_constraint('fk_application_current_decision', 'loan_applications', type_='foreignkey')
    op.drop_constraint('fk_application_current_version', 'loan_applications', type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_history_application_created', table_name='application_history')
    op.drop_table('application_history')
    op.drop_table('segment_assignments')
    op.drop_table('risk_scores')
    op.drop_table('explanations')
    op.drop_table('decisions')
    op.drop_index('ix_predictions_version_scored', table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('loan_outcomes')
    op.drop_table('feature_snapshot_sources')
    op.drop_table('source_snapshots')
    op.drop_index('ix_jobs_status_created', table_name='scoring_jobs')
    op.drop_table('scoring_jobs')
    op.drop_index('ix_loan_quotes_application_version', table_name='loan_quotes')
    op.drop_table('loan_quotes')
    op.drop_table('feature_snapshots')
    op.drop_index('ix_reports_requester_created', table_name='reports')
    op.drop_table('reports')
    op.drop_table('data_consents')
    op.drop_table('application_versions')
    op.drop_table('user_profiles')
    op.drop_table('policy_versions')
    op.drop_index('uq_model_deployment_active', table_name='model_deployments', postgresql_where=sa.text('retired_at IS NULL'))
    op.drop_table('model_deployments')
    op.drop_index('ix_applications_user_created', table_name='loan_applications')
    op.drop_index('ix_applications_status_submitted', table_name='loan_applications')
    op.drop_table('loan_applications')
    op.drop_index('ix_auth_sessions_user_id', table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_table('audit_events')
    op.drop_table('users')
    op.drop_index('ix_outbox_pending_created', table_name='outbox_events', postgresql_where=sa.text('dispatched_at IS NULL'))
    op.drop_table('outbox_events')
    op.drop_table('model_versions')
    # ### end Alembic commands ###

    op.execute('DROP FUNCTION creditiq_reject_mutation()')
    op.execute('DROP FUNCTION creditiq_protect_explanation()')
    op.execute('DROP FUNCTION creditiq_touch_updated_at()')
