"""installment intelligence snapshots

Revision ID: 20261003_0003
Revises: 20261003_0002
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '20261003_0003'
down_revision: Union[str, Sequence[str], None] = '20261003_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installment_imports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('source_kind', sa.Text(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('coverage_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_installment_imports_currency_format')),
    sa.CheckConstraint("jsonb_typeof(coverage_json) = 'object'", name=op.f('ck_installment_imports_coverage_json_shape')),
    sa.CheckConstraint("source_kind IN ('USER_DECLARED', 'DEMO')", name=op.f('ck_installment_imports_source_kind_values')),
    sa.CheckConstraint('window_start <= as_of', name=op.f('ck_installment_imports_window_order')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_installment_imports_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_installment_imports')),
    sa.UniqueConstraint('user_id', 'idempotency_key', name=op.f('uq_installment_imports_user_id_idempotency_key'))
    )
    op.create_index('ix_installment_imports_owner_created', 'installment_imports', ['user_id', 'created_at'], unique=False)
    op.create_table('installment_analyses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('import_id', sa.UUID(), nullable=False),
    sa.Column('calculation_version', sa.Text(), nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("jsonb_typeof(result_json) = 'object'", name=op.f('ck_installment_analyses_result_json_shape')),
    sa.ForeignKeyConstraint(['import_id'], ['installment_imports.id'], name=op.f('fk_installment_analyses_import_id_installment_imports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_installment_analyses')),
    sa.UniqueConstraint('import_id', 'calculation_version', name=op.f('uq_installment_analyses_import_id_calculation_version'))
    )
    op.create_table('installment_schedules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('import_id', sa.UUID(), nullable=False),
    sa.Column('account_ref', sa.Text(), nullable=False),
    sa.Column('installment_ref', sa.Text(), nullable=False),
    sa.Column('schedule_version', sa.Text(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.CheckConstraint("amount > 0 AND amount < 'Infinity'", name=op.f('ck_installment_schedules_amount_finite')),
    sa.ForeignKeyConstraint(['import_id'], ['installment_imports.id'], name=op.f('fk_installment_schedules_import_id_installment_imports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_installment_schedules')),
    sa.UniqueConstraint('id', 'import_id', name=op.f('uq_installment_schedules_id_import_id')),
    sa.UniqueConstraint('import_id', 'account_ref', 'installment_ref', name=op.f('uq_installment_schedules_import_id_account_ref_installment_ref'))
    )
    op.create_table('installment_payments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('import_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('event_ref', sa.Text(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.CheckConstraint("amount >= 0 AND amount < 'Infinity'", name=op.f('ck_installment_payments_amount_finite')),
    sa.ForeignKeyConstraint(['import_id'], ['installment_imports.id'], name=op.f('fk_installment_payments_import_id_installment_imports')),
    sa.ForeignKeyConstraint(['schedule_id', 'import_id'], ['installment_schedules.id', 'installment_schedules.import_id'], name=op.f('fk_installment_payments_schedule_id_installment_schedules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_installment_payments')),
    sa.UniqueConstraint('import_id', 'event_ref', name=op.f('uq_installment_payments_import_id_event_ref'))
    )
    # ### end Alembic commands ###


    for name in ('installment_imports', 'installment_schedules', 'installment_payments', 'installment_analyses'):
        op.execute(f'CREATE TRIGGER immutable_record BEFORE UPDATE OR DELETE ON {name} FOR EACH ROW EXECUTE FUNCTION creditiq_reject_mutation()')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('installment_payments')
    op.drop_table('installment_schedules')
    op.drop_table('installment_analyses')
    op.drop_index('ix_installment_imports_owner_created', table_name='installment_imports')
    op.drop_table('installment_imports')
    # ### end Alembic commands ###


